### ISSUE TITLE
Wisp Death Bonuses do not apply after stage they were gained in.

### ISSUE THREAD

**Issue by SorcererPonse** [RicoValdezio/WispDeathBonusPlugin#1]
Discovered that the accumulated bonuses applied from killing wisps only apply in the first stage. I visited the Bazaar after accumulating a large amount of aspects from killing wisps in Stage 1, and found out that they no longer applied.  I went to the Void Fields and gathered some more, but they still did not apply. Even progressing to Stage 2 still prevented them from applying. I will test and see if progressing to Stage 2 normally causes the same issue.

**Comment by RicoValdezio** [comment]
Issue resolved by commit 2958f86bf135219fae719fe001d18114ece7ba17
